apiVersion: v1
kind: Service
metadata:
  labels:
    app: logs-consumer
  name: logs-consumer
spec:
  type: LoadBalancer
  ports:
    - port: 5051
      targetPort: 5051
      protocol: TCP
  selector:
    app: logs-consumer